# Generated by Django 3.1.6 on 2021-02-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210209_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='time',
        ),
    ]
